import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useCategoriesQuery } from '../services/categories/categories.query';
import Link from 'next/link';

const Home: NextPage = () => {
  const { data, error, loading } = useCategoriesQuery();
  console.log(data)
  console.log(data?.getCategories?.result?.categories)
  if (loading) {
    return (
      <p>Loading</p>
    )
  }
  if (error) {
    return (
      <p>Error</p>
    )
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Walcart!</a>
        </h1>
        <Link href="/create">
          <button className="btn btn-primary">Create</button>
        </Link>

        <p className={styles.description}>
          A sister concern of{' '}
          <code className={styles.code}>Walton Bangladesh</code>
        </p>
        <div className={styles.grid}>
          {
            data && data?.getCategories?.result?.categories.map((category: any, index: number) => (
              <a key={index} className={styles.card}>
                {/* <h2>{category.name} &rarr;</h2> */}
                <p>{category.name}</p>
              </a>
            ))
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
